services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: smartpay
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
