services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: smartpay
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
      MYSQL_DATABASE: smartpay
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -usmartuser -psmartpass || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    volumes:
      - ./files:/app/files
      - .:/app

  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy   # ✅ așteaptă healthcheck
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306               # în rețeaua Docker, portul intern e 3306
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
      MYSQL_DATABASE: smartpay
    command: python init_db.py
    restart: "no"

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "8080:8080"

volumes:
  db_data:
